# Generated by Django 5.0.6 on 2024-05-30 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.BigIntegerField(default=0)),
                ('nome_fornecedor', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fun_nome', models.CharField(max_length=45)),
                ('fun_cpf', models.CharField(max_length=45)),
                ('fun_senha', models.CharField(max_length=45)),
                ('fun_funcao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_valor', models.FloatField()),
                ('pro_quantidade', models.IntegerField()),
                ('tb_fornecedores_for_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmanagement.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ven_horario', models.DateTimeField()),
                ('ven_valor_total', models.FloatField()),
                ('tb_funcionarios_fun_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmanagement.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ite_quantidade', models.IntegerField()),
                ('ite_valor_parcela', models.FloatField()),
                ('tb_produtos_pro_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmanagement.produto')),
                ('tb_vendas_ven_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmanagement.venda')),
            ],
        ),
    ]
