# Generated by Django 5.0.6 on 2024-05-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ite_valor_parcela',
            new_name='ite_valor_parcial',
        ),
    ]
