# Generated by Django 5.0.6 on 2024-05-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0002_rename_ite_valor_parcela_item_ite_valor_parcial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='tb_fornecedores_for_codigo',
            new_name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='pro_quantidade',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='pro_valor',
        ),
        migrations.AddField(
            model_name='produto',
            name='cor',
            field=models.TextField(default='Branco', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default='Camisa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(default='G', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(decimal_places=2, default='100', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venda',
            name='ven_valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
