# Generated by Django 5.0.6 on 2024-05-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0003_rename_tb_fornecedores_for_codigo_produto_fornecedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cli_nome', models.CharField(max_length=60)),
                ('cli_cpf', models.BigIntegerField()),
                ('cli_telefone', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='fun_cpf',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='fun_nome',
            field=models.CharField(max_length=60),
        ),
    ]
