# Generated by Django 5.0.6 on 2024-05-31 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0004_cliente_alter_funcionario_fun_cpf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='fun_cpf',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='fun_funcao',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='fun_nome',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='fun_senha',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(default=0, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(default='Joao', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(default=2314314135, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='usuario',
            field=models.OneToOneField(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stockmanagement.cargo'),
        ),

    ]
