# Generated by Django 5.0.6 on 2024-05-31 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0005_cargo_remove_funcionario_fun_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='funcao',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='stockmanagement.cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
