# Generated by Django 5.0.6 on 2024-06-01 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0006_alter_funcionario_funcao_alter_funcionario_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='ven_horario',
            new_name='horario',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='ven_valor_total',
            new_name='valor_total',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='tb_funcionarios_fun_codigo',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='stockmanagement.funcionario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='funcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmanagement.cargo'),
        ),
    ]
