# Generated by Django 5.0.6 on 2024-06-01 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0007_rename_ven_horario_venda_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stockmanagement.funcionario'),
        ),
    ]
