# Generated by Django 5.0.6 on 2024-06-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0008_alter_venda_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
