# Generated by Django 5.0.6 on 2024-06-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0010_itenspedido_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='horario',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
