# Generated by Django 5.0.6 on 2024-06-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0014_alter_funcionario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenspedido',
            name='preco_parcial',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
