# Generated by Django 5.0.6 on 2024-06-01 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0016_venda_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cli_cpf',
            new_name='cpf',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cli_nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cli_telefone',
            new_name='telefone',
        ),
    ]
