# Generated by Django 5.0.6 on 2024-06-01 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0017_rename_cli_cpf_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenspedido',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockmanagement.venda'),
        ),
        migrations.AlterField(
            model_name='itenspedido',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockmanagement.produto'),
        ),
    ]
