# Generated by Django 5.0.6 on 2024-06-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0019_alter_cargo_cargo_alter_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
